name: My First Scheduled Job

on:
  schedule:
    - cron: '3 4 * * *'    # 1-collect → 07:03 МСК
  workflow_dispatch:        # + кнопка ручного запуска

jobs:
  my-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print welcome message
        run: echo "Привет! Этот скрипт запустился автоматически по расписанию!"

